version: '3.3'
services:
 
  webapplication9:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5088:80"
    image: ${DOCKER_REGISTRY}webapplication9
    build: 
       context: .
       dockerfile: WebApplication9/Dockerfile